name: example
version: 1.0.0
homepage: https://github.com/Solido/Flutter-BlurHash
authors:
  - Robert Felker <flutter@robbieone.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  inview_notifier_list: ^2.0.0
  google_fonts: ^2.1.0
  flutter_blurhash: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true